In [1]:
import cv2

In [2]:
img = cv2.imread("face.jpg")#name of image is face

#to maek the image greyscale
#img = cv2.imread("face.jpg",cv2.IMREAD_GRAYSCALE)
#cv2.imread("face.jpg",cv2.IMREAD_COLOR)
img.shape
#if you print(img) #printed as numpy array
#if shape is printed by print(img.shape) #-> width,height,(3 for color)

(562, 750, 3)

In [3]:
#cv2.imshow('Mr X',img)#to give name to the dialogue box opened

In [4]:
#cv2.waitKey(0) for holding of the box
#-1 is the output when the image is closed

In [5]:
#cv2.imwrite('abc.jpg',img)#for making it discolor  #used when changing color of the pic #creates the final image from webcam
#cv2.destroyAllWindows()#to close the picture

In [6]:
cv2.rectangle(img,(244,310),(334,365),(0,0,255),3)#parameters names are image (nameOfImage, (start x,y)  , (end x,y) , color, thickness)
cv2.imshow('Blog',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

'''if -1 is as a parameter for thickness the box gets filled'''
#for drawing a circle
'''cv2.circle(img,(130,50),50,(0,0,255),3) (end x,y has only one parameter)'''
#for drawing a line
'''cv2.line(img,(50,200),(50,450),(0,0,255),10)'''

'cv2.line(img,(50,200),(50,450),(0,0,255),10)'

### VIDEO WRITER BELOW

In [7]:
#cam = cv2.VideoCapture(0)#0 for reading the video filer

In [8]:
#FACES DETECTION CODE WHICH INCLUDE haarcascade_frontalface_default file as learning data

## FACE RECOGNITION

In [9]:
import cv2
fd = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
cam = cv2.VideoCapture(0)

while True:
    ret , img = cam.read()
    gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = fd.detectMultiScale(gray,1.3,5,minSize = (30,30))
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,0),2)
    cv2.imshow('Faces',img)
    if(cv2.waitKey(1) == ord('q')):
        break
cam.release()
cv2.destroyAllWindows()

In [10]:
"""while cam.isOpened():#checking the camera on or off
    index, img = cam.read()#returns image index
    if index:
        nimg = cv2.cvtColor(img,cv2.IMREAD_COLOR)
        cv2.imshow('frame',nimg)#frame reader for the size of image
        cv2.imwrite('abc.jpg',nimg)
    if cv2.waitKey(1) & 0xFF == ord('q'):#unicode value character 0xFF  #helps in overwriting the close button
        break
cam.release()
cv2.destroyAllWindows()"""

"while cam.isOpened():#checking the camera on or off\n    index, img = cam.read()#returns image index\n    if index:\n        nimg = cv2.cvtColor(img,cv2.IMREAD_COLOR)\n        cv2.imshow('frame',nimg)#frame reader for the size of image\n        cv2.imwrite('abc.jpg',nimg)\n    if cv2.waitKey(1) & 0xFF == ord('q'):#unicode value character 0xFF  #helps in overwriting the close button\n        break\ncam.release()\ncv2.destroyAllWindows()"

In [11]:
#working on the face recognition for images and videos

### VIDEO WRITING

In [12]:
#15  is the best apperture for videos
#waitKey always display the video when the value is 0 otherwise it doesn't

### RECORDING FROM THE VIDEO CAMERA

In [13]:
import cv2
cam=cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*'XVID')
out = cv2.VideoWriter('video12.avi',fourcc, 15.0, (640,480))
while cam.isOpened():
    
    i, frame = cam.read()
    if i:
        gray = cv2.cvtColor(frame, cv2.IMREAD_COLOR)
        out.write(frame)
        cv2.imshow('Title',gray)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cam.release()
cv2.destroyAllWindows()    

### VIDEO CAMERA FEATURES RECOG.

In [14]:
import cv2
face_cascade = cv2.CascadeClassifier(r"C:\Users\vaibhav\Desktop\PY_ML_2019\Facial Recog\haarcascade_frontalface_default.xml")
eye_cascade = cv2.CascadeClassifier(r"C:\Users\vaibhav\Desktop\PY_ML_2019\Facial Recog\haarcascade_eye (1).xml")
cap = cv2.VideoCapture(0)

while True:
    ret, img = cap.read()
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray,1.3,5) 
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray = gray[y:y+h, x:x+w]
        print(roi_gray)
        roi_color = img[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color, (ex,ey),(ex+ew, ey+eh), (0,255,0),2)
    cv2.imshow('img',img)
    k = cv2.waitKey(30) & 0Xff
    if k ==27:
        break
cap.release()
cv2.destroyAllWindows()

[[193 190 190 ... 180 182 181]
 [194 192 193 ... 178 180 180]
 [194 192 193 ... 174 173 174]
 ...
 [ 10   9   8 ...  31  28  25]
 [  8   8   9 ...  30  28  25]
 [  5   6   9 ...  30  30  27]]
[[191 193 196 ... 175 176 183]
 [196 196 194 ... 180 180 180]
 [194 196 196 ... 179 179 179]
 ...
 [  7   7   7 ...  29  28  28]
 [  7   7   7 ...  28  27  27]
 [  8   9  10 ...  29  30  31]]
[[187 188 193 ... 176 176 176]
 [188 189 197 ... 179 179 178]
 [188 189 196 ... 181 180 179]
 ...
 [ 10   9  10 ...  28  29  29]
 [  9   7   8 ...  27  28  29]
 [  8   6   6 ...  29  30  30]]
[[184 193 195 ... 182 182 180]
 [186 189 195 ... 181 179 180]
 [186 190 195 ... 181 179 180]
 ...
 [  9  11  11 ...  27  28  30]
 [  9  11  11 ...  27  29  31]
 [  9  10  10 ...  29  31  31]]
[[193 187 185 ... 179 179 179]
 [195 190 188 ... 179 179 179]
 [194 192 190 ... 180 180 180]
 ...
 [  7   7   7 ...  28  29  30]
 [ 10   9   9 ...  29  30  31]
 [ 11  10   9 ...  30  30  31]]
[[191 191 191 ... 179 177 176]
 [192 192

[[193 194 195 ... 153 166 179]
 [194 195 195 ... 154 163 188]
 [194 194 195 ... 175 166 175]
 ...
 [ 32  30  24 ...  81  79  78]
 [ 33  30  25 ...  62  70  76]
 [ 37  32  26 ...  65  69  73]]
[[194 196 189 ... 177 178 178]
 [192 192 191 ... 170 177 178]
 [191 191 193 ... 175 177 178]
 ...
 [ 23  20  19 ...  89  94 106]
 [ 22  19  19 ...  83  80  68]
 [ 20  17  19 ...  75  85  80]]
[[194 194 194 ... 163 181 174]
 [194 194 194 ... 165 184 174]
 [194 194 194 ... 166 186 175]
 ...
 [ 32  25  20 ...  66  69  72]
 [ 30  23  19 ...  59  61  63]
 [ 31  24  19 ...  52  58  64]]
[[191 188 191 ... 172 178 178]
 [191 186 189 ... 178 178 185]
 [192 189 190 ... 173 173 175]
 ...
 [ 22  20  18 ...  68  75  81]
 [ 22  20  19 ...  65  69  73]
 [ 23  21  21 ...  70  69  66]]
[[196 195 194 ... 180 178 179]
 [196 195 194 ... 176 176 182]
 [193 193 193 ... 172 175 181]
 ...
 [ 26  25  23 ...  77  76  75]
 [ 22  21  21 ...  68  68  68]
 [ 17  18  19 ...  70  69  67]]
[[192 194 192 ... 181 178 178]
 [192 195

[[191 191 189 ... 179 180 179]
 [190 190 188 ... 180 181 180]
 [191 191 189 ... 179 180 179]
 ...
 [  8   7   4 ...  27  30  32]
 [  8   7   4 ...  27  30  32]
 [  7   6   6 ...  27  29  31]]
[[191 194 192 ... 174 175 176]
 [191 194 194 ... 177 174 176]
 [190 191 191 ... 182 175 177]
 ...
 [ 11  11  11 ...  28  31  31]
 [ 10  10  11 ...  29  31  32]
 [  8  10  11 ...  31  32  32]]
[[193 192 191 ... 178 175 179]
 [192 191 190 ... 178 177 181]
 [191 190 189 ... 178 178 182]
 ...
 [ 11  11  10 ...  26  29  34]
 [ 10  10   9 ...  26  28  31]
 [ 10  10   9 ...  27  27  27]]
[[190 189 189 ... 177 178 176]
 [192 191 191 ... 178 182 178]
 [194 194 193 ... 178 180 178]
 ...
 [ 12   9   8 ...  31  32  35]
 [ 10   6   6 ...  29  29  34]
 [ 10   9   8 ...  32  34  31]]
[[191 191 192 ... 176 182 187]
 [194 194 194 ... 177 178 182]
 [193 193 193 ... 182 177 176]
 ...
 [ 12  12  12 ...  26  28  31]
 [ 11  12  12 ...  28  30  33]
 [ 11  13  12 ...  29  27  30]]
[[190 192 192 ... 179 176 177]
 [190 191

[[191 191 195 ... 182 179 179]
 [192 192 194 ... 184 177 178]
 [193 193 194 ... 179 175 177]
 ...
 [ 87  85  75 ...  61  69  68]
 [ 87  74  68 ...  56  56  60]
 [ 82  77  63 ...  59  60  60]]
[[196 194 191 ... 180 182 183]
 [195 194 193 ... 177 182 182]
 [195 196 194 ... 178 181 182]
 ...
 [ 83  79  79 ...  61  69  75]
 [ 79  77  77 ...  51  66  70]
 [ 80  81  68 ...  55  62  69]]
[[193 195 196 ... 182 181 181]
 [193 194 195 ... 180 180 181]
 [193 194 195 ... 179 180 181]
 ...
 [ 59  56  56 ...  50  46  44]
 [ 50  48  48 ...  44  40  38]
 [ 46  46  47 ...  40  36  35]]
[[193 194 194 ... 182 182 181]
 [194 194 193 ... 181 180 180]
 [194 194 193 ... 180 180 179]
 ...
 [ 54  46  34 ...  35  36  39]
 [ 33  28  23 ...  35  36  40]
 [ 16  16  15 ...  33  35  38]]
[[191 192 193 ... 181 180 179]
 [195 195 195 ... 183 183 183]
 [194 193 192 ... 183 184 184]
 ...
 [ 33  29  28 ...  34  37  41]
 [ 38  35  35 ...  36  36  40]
 [ 34  30  28 ...  37  36  39]]
[[193 192 192 ... 179 179 180]
 [192 192

[[192 191 196 ... 184 180 180]
 [192 191 200 ... 171 179 179]
 [193 193 199 ... 163 179 179]
 ...
 [ 94  89  79 ...  61  67  74]
 [ 86  79  76 ...  67  63  67]
 [ 87  75  65 ...  53  60  61]]
[[194 195 194 ... 177 178 176]
 [195 195 193 ... 180 179 179]
 [194 194 192 ... 181 181 181]
 ...
 [ 48  47  44 ...  37  35  35]
 [ 41  42  40 ...  35  34  35]
 [ 36  38  39 ...  34  34  35]]
[[193 190 192 ... 181 179 179]
 [191 187 189 ... 180 181 181]
 [195 190 191 ... 181 184 183]
 ...
 [ 50  48  46 ...  40  39  39]
 [ 47  44  40 ...  38  37  36]
 [ 39  39  39 ...  32  34  36]]
[[191 179 190 ... 183 184 181]
 [189 192 193 ... 180 180 184]
 [193 191 192 ... 179 180 183]
 ...
 [ 33  29  27 ...  35  37  37]
 [ 33  29  25 ...  36  38  38]
 [ 28  27  23 ...  38  40  40]]
[[194 191 191 ... 183 183 181]
 [194 192 192 ... 182 183 181]
 [195 196 196 ... 182 182 180]
 ...
 [ 18  13  16 ...  22  28  32]
 [ 15  15  15 ...  24  28  29]
 [ 16  15  14 ...  24  29  31]]
[[190 191 191 ... 180 180 180]
 [190 190

[[193 196 191 ... 180 180 178]
 [200 196 195 ... 181 181 179]
 [198 195 194 ... 179 180 179]
 ...
 [ 12   8   8 ...  33  30  28]
 [ 11   5   5 ...  32  28  27]
 [  8   8   8 ...  27  25  26]]
[[194 192 192 ... 179 179 179]
 [193 192 192 ... 180 180 179]
 [192 190 189 ... 179 179 179]
 ...
 [  9   6   9 ...  25  31  34]
 [  9   5   7 ...  24  30  34]
 [ 10   6   8 ...  23  29  34]]
[[190 190 191 ... 179 181 180]
 [190 190 190 ... 180 178 173]
 [190 190 190 ... 178 175 171]
 ...
 [  5   5   6 ...  20  23  27]
 [  5   6   7 ...  20  22  26]
 [  8   8   9 ...  20  22  25]]
[[192 192 192 ... 181 182 182]
 [193 193 193 ... 176 178 179]
 [194 193 193 ... 178 180 180]
 ...
 [ 12  11  10 ...  23  26  32]
 [ 10  10  10 ...  22  28  32]
 [  9   9   9 ...  21  26  30]]
[[191 190 191 ... 177 178 179]
 [191 191 190 ... 178 178 176]
 [191 190 188 ... 179 177 171]
 ...
 [ 15  10  10 ...  34  35  31]
 [ 16  10  11 ...  33  34  29]
 [ 16  12  12 ...  31  32  29]]
[[193 194 192 ... 174 176 180]
 [193 193

[[195 191 187 ... 178 179 180]
 [196 192 187 ... 179 179 180]
 [194 191 188 ... 180 178 179]
 ...
 [ 11  12  12 ...  32  34  36]
 [ 12  11  11 ...  29  32  35]
 [ 10   9   7 ...  28  30  34]]
[[195 135  83 ... 184 183 183]
 [200 132  77 ... 182 181 183]
 [179 121 111 ... 179 179 180]
 ...
 [ 10  12  13 ...  20  18  17]
 [ 12  12  12 ...  20  19  18]
 [ 12  12  13 ...  20  19  18]]
[[ 90  91  63 ... 180 180 181]
 [ 81  76  67 ... 180 180 180]
 [ 74  70  64 ... 179 179 179]
 ...
 [ 11  11  10 ...  31  34  37]
 [ 10  10  10 ...  31  34  37]
 [ 11  11  10 ...  32  34  36]]
[[192 191 191 ... 184 183 182]
 [192 191 191 ... 184 182 180]
 [190 189 189 ... 184 181 178]
 ...
 [  8   8   8 ...  34  34  35]
 [ 10   9   8 ...  31  32  34]
 [ 12  10   8 ...  30  31  33]]
[[189 190 191 ... 177 179 182]
 [187 190 192 ... 179 178 180]
 [188 189 190 ... 179 179 179]
 ...
 [ 12  12  11 ...  39  41  42]
 [  8   8   8 ...  35  38  39]
 [  6   7   7 ...  36  37  39]]


### FEATURES RECOG. FROM DOWNLOADED PHOTO

In [15]:
### FOR PICTURE FEATURES CAPTURE

import cv2 as cv

face_cascade = cv.CascadeClassifier(r"C:\Users\vaibhav\Desktop\PY_ML_2019\Facial Recog\haarcascade_frontalface_default.xml")
eye_cascade = cv.CascadeClassifier(r"C:\Users\vaibhav\Desktop\PY_ML_2019\Facial Recog\haarcascade_eye (1).xml")
img = cv.imread('face3.jpg')
gray = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
faces = face_cascade.detectMultiScale(gray,1.3,5)
for (x,y,w,h) in faces:
    cv.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
    roi_gray  = gray[y:y+h, x:x+w]
    roi_color = img[y:y+h, x:x+w]
    
    eyes = eye_cascade.detectMultiScale(roi_gray)
    for(ex,ey,ew,eh) in eyes:
        cv.rectangle(roi_color, (ex,ey),(ex+ew,ey+eh),(0,0,255),2)
    cv.imshow('img',img)
    k = cv.waitKey(30) & 0Xff
    if k == 27:
        break
cv.imshow('img',img)
cv.waitKey(0)

-1

In [16]:
#MODEL_MEAN_VALUE pre defined mean which is used in gender detection 
#blob binary large OBject
         

### DRAWING AT THE IMAGE 

In [17]:
import cv2
import numpy as np
img = cv2.imread('face3.jpg', cv2.IMREAD_COLOR)
pts = np.array([[10,5],[20,30],[900,20],[50,10],[70,30]], np.int32)
pts = pts.reshape((-1,1,2))
img = cv2.polylines(img,[pts],True,(0,255,255))
cv2.imshow('title',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

### Writing at an IMAGE

In [18]:
# to write the text on an image
import cv2
import numpy as np

img = cv2.imread('face3.jpg', cv2.IMREAD_COLOR)
font = cv2.FONT_HERSHEY_COMPLEX
cv2.putText(img,'OpenCv', (30,40), font, 2 ,(0,0,255),1,cv2.LINE_8)

cv2.imshow('title',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [19]:
#NOT USEFUL NOW
"""import cv2
import numpy as np
#MOUSE CALLBACK FUNCTION
def draw_circle(event,x,y,flags,param):
    if event == cv2.EVENT_LBUTTONDBLCLK:
        cv2.circle(img,(x,y),50,(0,25,75),-1)
#CREATE A BLACK IMAGE, A WINDOW AND BIND THE FUNCTION image WINDOW
img = np.zeros((512,512,3))
cv2.namedWindow('image')
cv2.setMouseCallback('image',draw_circle)

while(1):
    cv2.imshow('image',img)
    if cv2.waitKey(1) & 0Xff == 27:
        break
cv2.destroyAllWindows()"""

"import cv2\nimport numpy as np\n#MOUSE CALLBACK FUNCTION\ndef draw_circle(event,x,y,flags,param):\n    if event == cv2.EVENT_LBUTTONDBLCLK:\n        cv2.circle(img,(x,y),50,(0,25,75),-1)\n#CREATE A BLACK IMAGE, A WINDOW AND BIND THE FUNCTION image WINDOW\nimg = np.zeros((512,512,3))\ncv2.namedWindow('image')\ncv2.setMouseCallback('image',draw_circle)\n\nwhile(1):\n    cv2.imshow('image',img)\n    if cv2.waitKey(1) & 0Xff == 27:\n        break\ncv2.destroyAllWindows()"